name: Rebase from upstream
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '* * * * *'
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rebase from upstream
        run: |
          git config --global user.name 'Jean-Olivier Irisson'
          git config --global user.email 'irisson@normalesup.org'

          # get changes
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/TheAlexBarth/EcotaxaTools.git
          git fetch upstream

          git rebase upstream/main
          git push origin main
